#!/bin/bash
#set -x

date

basedir=$(dirname $0)
while read ip mountpoint dest
do
    if [[ -z ${ip} || ${ip:0:1} == \# ]]; then
        # empty or commented line
        continue
    fi

    touchfile=${basedir}/$(basename ${mountpoint})
    echo "ip=${ip} mountpoint=${mountpoint} dest=${dest} touchfile=${touchfile}"

    ping -c3 ${ip} >/dev/null
    if [ "$?" == 0 ]; then
        echo "${ip} is up"
    else
        echo "${ip} is down - skipping"
        continue
    fi

    if [ ! -f ${touchfile} ]; then
        touch -t197001010000.00 ${touchfile}
    fi
    if [ $(( (`date +%s` - `stat -L --format %Y ${touchfile}`) > (60*60*24) )) == 1 ]; then
        echo "last successful collect for ${mountpoint} > 1 day ago"
    else
        echo "last successful collect for ${mountpoint} < 1 day ago - skipping"
        continue
    fi

    rsync_command="rsync -av --progress ${mountpoint}/ ${dest}"

    if [ "$(pgrep -f "${rsync_command}")" ]; then
        echo "collect already running for ${mountpoint} - skipping"
        continue
    else
        echo "no collect running for ${mountpoint}"
    fi

    # does the mount point exist?
    if [ ! -d ${mountpoint} ]; then
        echo "${mountpoint} does not exist; creating"
        mkdir -v ${mountpoint}
    else
        echo "${mountpoint} exists"
    fi

    # is the directory mounted?  Test for 'is not empty'
    if [ ! "$(ls -A ${mountpoint})" ]; then
        echo "${mountpoint} is not mounted; mounting"
        umount ${mountpoint}
        mount ${mountpoint}
    else
        echo "${mountpoint} is mounted"
    fi

    # OK - kick it off in background
    eval ${rsync_command} && touch ${touchfile} &

done <${basedir}/sources
